apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}-configmap
data:
    mongo_host: "{{ .Values.mongodb.service.nameOverride }}"
    mongo_port: "{{ .Values.mongodb.service.ports.mongodb }}"
    mongo_auth: "{{ .Values.mongodb.auth.enabled }}"
