apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "helm.fullname" . }}-configmap
                  key: mongo_host
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "helm.fullname" . }}-configmap
                  key: mongo_port
            - name: MONGO_AUTH__ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "helm.fullname" . }}-configmap
                  key: mongo_auth
            - name: MONGO_AUTH__USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm.fullname" . }}-secret
                  key: username
            - name: MONGO_AUTH__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm.fullname" . }}-secret
                  key: mongodb-root-password
